### ISSUE TITLE
Google Drive folder with pretrained models appears to be empty

### ISSUE THREAD

**Issue by saharNooby** [elad-amrani/self-classifier#1]
Hi, I've followed a link from README.md: https://drive.google.com/drive/folders/1o8M1cSVnhsMsdiRejj0DweWs2mhtP57F?usp=sharing

It appears like the folder is empty.

How can I access pretrained models?

**Comment by elad-amrani** [comment]
Thanks for letting me know 🙏🏽
I will upload the files in the following days.

**Comment by elad-amrani** [comment]
Hi @saharNooby,
Sorry for the delay. The models are there now.

Enjoy!

**Comment by saharNooby** [comment]
Thanks!
